services:
  mylocaldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
  car-dealership:
    image: car-dealership
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mylocaldb:3306/dealership?autoReconnect=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "password"
    build: .
    depends_on:
      - mylocaldb
