version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
    - MYSQL_ROOT_PASSWORD:password
    - MY_SQL_DATABASE:dealership
    ports:
      - '3307:3306'
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dealership
      SPRING_DATASOURCE_USERNAME:root
      SPRING_DATASOURCE_PASSWORD:password
    build:
      context:"./"
      dockerfile:"Dockerfile"
    depends_on:
      - mysql-standalone